name: CI-CD DevSecOps Shift-Left

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Secret Scan (TruffleHog)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          extra_args: --only-verified

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 

  build_and_scan:
    needs: security_analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devsecops-api:${{ github.sha }} .

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-api:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
      - name: Generate Security Summary
        if: always() # S'exécute même si le scan échoue
        run: |
          echo "## 🛡️ Rapport de Sécurité Trivy" >> $GITHUB_STEP_SUMMARY
          echo "Analyse effectuée sur l'image : devsecops-api:${{ github.sha }}"
      - name: Push Image (Simulation)
        run: echo "L'image est propre et sécurisée. Prête pour le déploiement !"

  deploy:
    needs: build_and_scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag and Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: devsecops-api
          IMAGE_TAG: latest
        run: |
          docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name devsecops-api-lambda \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/devsecops-api:latest \
            --region eu-west-3